<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TowerfallPath>D:\SteamLibrary\steamapps\common\TowerFall\FortRise</TowerfallPath>
    <ModLoaderPath>D:\SteamLibrary\steamapps\common\TowerFall\FortRise</ModLoaderPath>
    
    <ModVersion>2.0.0</ModVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$(DefineConstants.Contains('ITCHIO'))">
    <TowerfallPath>D:\Games\TowerFall-FortRise5</TowerfallPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
<!--    <OutputPath Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">$(TowerfallPath)\Mods\$(AssemblyName)</OutputPath>-->
<!--    <OutputPath Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">$(TowerfallPath)\Mods\$(AssemblyName)-Debug</OutputPath>-->
  </PropertyGroup>
  
  <ItemGroup>
    <Content Include="Content/Atlas/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content/TeamBanners/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content/CustomArchers/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CustomArchers/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="meta.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

<!--  <ItemGroup>-->
<!--    <Reference Include="FNA, Version=23.10.0.0, Culture=neutral, PublicKeyToken=null">-->
<!--      <HintPath>D:\Games\TowerFall-FortRise\FNA.dll</HintPath>-->
<!--    </Reference>-->
<!--    <Reference Include="TowerFall, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">-->
<!--      <HintPath>D:\SteamLibrary\steamapps\common\FortRise\TowerFall.Patch.dll</HintPath>-->
<!--    </Reference>-->
<!--  </ItemGroup>-->

  <ItemGroup>
    <Compile Remove="Content\Atlas\**" />
    <Compile Remove="OldBeinpexVersion\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Content\Atlas\**" />
    <EmbeddedResource Remove="OldBeinpexVersion\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Content\Atlas\**" />
    <None Remove="OldBeinpexVersion\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TowerFall, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
      <HintPath>D:\SteamLibrary\steamapps\common\TowerFall\FortRise\TowerFall.Patch.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FortRise.Configuration" Version="1.5.6" />
  </ItemGroup>
</Project>
